#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -rf constant/extendedFeatureEdgeMesh > /dev/null 2>&1
rm -f constant/triSurface/duneModel_0_run_02.eMesh > /dev/null 2>&1
rm -f constant/triSurface/bldg_Model_00_run_00.eMesh > /dev/null 2>&1
rm -f constant/triSurface/terrain_Model_00_run_00.eMesh > /dev/null 2>&1
rm -f constant/polyMesh/boundary > /dev/null 2>&1

#------------------------------------------------------------------------------
